### ISSUE TITLE
可以介绍下学习顺序吗？

### ISSUE THREAD

**Issue by gislu** [pirDOL/6.824#1]
感觉有些杂乱额，不知道从哪里开始看。。。

**Comment by pirDOL** [comment]
timeline大体上是根据6.824的课表，每节课或者每几节课是一个专题，具体内容包括：论文、讲义、作业。

**Comment by pirDOL** [comment]
@gislu 
开始学的时候还是2015年，到2017年都没做完，最近打算重新开始做2017年的作业，调整了一下学习方法更新到README.md，欢迎交流~
